import React from 'react';
import { ExtractedBillData } from '../types';
import { Download, Share2, Printer } from 'lucide-react';

interface BillPreviewProps {
  data: ExtractedBillData;
  onReset: () => void;
}

export const BillPreview: React.FC<BillPreviewProps> = ({ data, onReset }) => {
  return (
    <div className="w-full max-w-4xl mx-auto bg-white shadow-2xl rounded-lg overflow-hidden border border-gray-200 animate-fade-in">
      {/* Action Bar */}
      <div className="bg-gray-800 text-white p-4 flex justify-between items-center no-print">
        <div className="text-sm font-medium text-gray-300">CFD Invoice</div>
        <div className="flex gap-3">
            <button onClick={() => window.print()} className="flex items-center gap-2 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-sm transition-colors">
            <Printer size={16} /> Print
          </button>
          <button onClick={onReset} className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 rounded text-sm font-medium transition-colors">
            Scan New
          </button>
        </div>
      </div>

      {/* Bill Content */}
      <div className="p-8 md:p-12 print:p-0">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 pb-8 border-b-2 border-gray-100">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 uppercase tracking-wide">{data.documentType || 'INVOICE'}</h1>
            <p className="text-gray-500 mt-1">Generated by <span className="font-semibold text-indigo-600">CFD Invoice</span></p>
          </div>
          <div className="mt-4 md:mt-0 text-right">
            <div className="text-sm text-gray-500">Document No.</div>
            <div className="text-xl font-mono font-semibold text-gray-800">{data.documentNumber || 'N/A'}</div>
            <div className="text-sm text-gray-500 mt-2">Date</div>
            <div className="font-medium text-gray-800">{data.date || 'N/A'}</div>
          </div>
        </div>

        {/* Parties */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
          <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">From (Consignor)</h3>
            <div className="font-bold text-lg text-gray-900">{data.sender.name || 'Unknown Sender'}</div>
            <div className="text-gray-600 mt-2 whitespace-pre-wrap">{data.sender.address}</div>
            {data.sender.taxId && (
              <div className="mt-3 text-sm text-gray-500">
                <span className="font-medium">Tax ID:</span> {data.sender.taxId}
              </div>
            )}
          </div>
          <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">To (Consignee)</h3>
            <div className="font-bold text-lg text-gray-900">{data.receiver.name || 'Unknown Receiver'}</div>
            <div className="text-gray-600 mt-2 whitespace-pre-wrap">{data.receiver.address}</div>
            {data.receiver.taxId && (
              <div className="mt-3 text-sm text-gray-500">
                <span className="font-medium">Tax ID:</span> {data.receiver.taxId}
              </div>
            )}
          </div>
        </div>

        {/* Items Table */}
        <div className="mb-8 overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-800 text-white">
                <th className="py-3 px-4 rounded-tl-lg font-medium text-sm">Description</th>
                <th className="py-3 px-4 font-medium text-sm text-right">Qty</th>
                <th className="py-3 px-4 font-medium text-sm text-right">Rate</th>
                <th className="py-3 px-4 rounded-tr-lg font-medium text-sm text-right">Amount</th>
              </tr>
            </thead>
            <tbody>
              {data.items.length > 0 ? (
                data.items.map((item, index) => (
                  <tr key={index} className="border-b border-gray-100 hover:bg-gray-50">
                    <td className="py-3 px-4 text-gray-800">{item.description}</td>
                    <td className="py-3 px-4 text-gray-600 text-right font-mono">{item.quantity}</td>
                    <td className="py-3 px-4 text-gray-600 text-right font-mono">{item.rate}</td>
                    <td className="py-3 px-4 text-gray-900 font-medium text-right font-mono">{item.amount}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={4} className="py-6 text-center text-gray-400 italic">No valid items detected</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="flex flex-col md:flex-row justify-between items-start border-t border-gray-200 pt-6">
          <div className="mb-6 md:mb-0 max-w-xs">
            <h4 className="font-bold text-sm text-gray-700 mb-2">Notes / Remarks</h4>
            <p className="text-sm text-gray-500 italic">
              {data.notes || "No additional remarks provided in the document."}
            </p>
          </div>
          
          <div className="w-full md:w-80">
            <div className="flex justify-between py-2 text-gray-600">
              <span>Subtotal</span>
              <span className="font-mono">{data.currency} {data.subtotal}</span>
            </div>
            <div className="flex justify-between py-2 text-gray-600 border-b border-gray-200 mb-2">
              <span>Tax / GST</span>
              <span className="font-mono">{data.currency} {data.taxAmount}</span>
            </div>
            <div className="flex justify-between py-3 text-xl font-bold text-gray-900">
              <span>Total</span>
              <span>{data.currency} {data.totalAmount}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center pt-8 border-t border-gray-100">
           <p className="text-gray-400 text-sm">Digitally extracted by CFD Invoice • {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
};